# Configurações de build para o Netlify
[build]
  base = "/"
  publish = "dist/chamados-para-curar"
  command = "CI='' npm run netlify:build"

# Configurações de ambiente para o Node.js
[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.1.0"
  CI = "false"

# Configurações de redirecionamento para aplicações Single Page Application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Configurações de cabeçalhos personalizados
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=31536000"
