[build]
  publish = "dist/chamados-para-curar"
  command = "npm run netlify:build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.9.0"
  NPM_VERSION = "10.1.0"
